version: '2'
services:
  kong-lb:
    image: rancher/lb-service-haproxy:v0.7.15
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      crate.service.name: crate-kong.kong-lb
      io.rancher.container.create_agent: 'true'
  kong-database:
    image: dockerhub.cisco.com/crate-docker/kong-service-db:v0.34-1-alpine-r3
    labels:
      crate.service.name: crate-kong.kong-database
  apikey-service:
    image: dockerhub.cisco.com/crate-docker/apikey-service:v1.0.2
    labels:
      crate.service.name: crate-kong.apikey-service
  kong:
    image: dockerhub.cisco.com/crate-docker/kong-service-api:v0.34-1-alpine-r3
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_API_URI: http://crate-kong.formal-chicken-dinner.crate.farm/api
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DATABASE: postgres
      KONG_LICENSE_DATA: 'license'
      KONG_PG_HOST: kong-database
      KONG_PORTAL: 'on'
      KONG_PORTAL_API_LISTEN: 0.0.0.0:8004
      KONG_PORTAL_GUI_LISTEN: 0.0.0.0:8003
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_TRUSTED_IPS: 0.0.0.0/0,::/0
      KONG_VITALS: 'false'
    links:
    - kong-database:kong-database
    labels:
      crate.service.name: crate-kong.kong

